{
 "title": "main host",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPULA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "CPULA 1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "CPULA 5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "CPULA 15"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{ job=\"nodeexporter\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{ job=\"nodeexporter\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance, mode) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "File system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{ job=\"nodeexporter\",mountpoint=\"/\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{ job=\"nodeexporter\",mountpoint=\"/\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}